version: '3.8'

services:
  frontend:
    image: ${ENV}-react-client-image
    container_name: ${ENV}-react-client
    build:
      context: ./react-client
      dockerfile: Dockerfile
      args:
        VITE_NODE_ENV: ${VITE_NODE_ENV}
        VITE_APP_API_URL: ${VITE_APP_API_URL}
        VITE_API_LOGIN_URL: ${VITE_API_LOGIN_URL}
        VITE_OPENIDDICT_CLIENT_ID: ${VITE_OPENIDDICT_CLIENT_ID}
        VITE_OPENIDDICT_GRANT_TYPE: ${VITE_OPENIDDICT_GRANT_TYPE}
        VITE_FALLBACK_THEME: ${VITE_FALLBACK_THEME}
        VITE_GEOCODING_API_KEY: ${VITE_GEOCODING_API_KEY}
    ports:
      - '80:80'
    networks:
      - app-network
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  sql-server:
    container_name: ${ENV}-sql-server
    image: ${ENV}-sql-server-image
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - 1433:1433
    networks:
      - app-network

networks:
  app-network:
    name: linkedin-map-copy-network
