IF NOT EXISTS (
  SELECT
    *
  FROM
    INFORMATION_SCHEMA.TABLES
  WHERE
    TABLE_SCHEMA = 'map'
    AND TABLE_NAME = 'Location'
) BEGIN CREATE TABLE map.Location (
  Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  Longitude DECIMAL(12, 9) NOT NULL,
  Latitude DECIMAL(12, 9) NOT NULL,
  Street VARCHAR(255) NULL,
  RoadNumber NVARCHAR(255) NULL,
  Suburban VARCHAR(255) NULL,
  City VARCHAR(255) NULL,
  PostalCode NVARCHAR(127) NULL
);

END