IF NOT EXISTS (
  SELECT
    *
  FROM
    INFORMATION_SCHEMA.TABLES
  WHERE
    TABLE_SCHEMA = 'work'
    AND TABLE_NAME = 'Company'
) BEGIN CREATE TABLE WORK.Company (
  Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  Name VARCHAR(127) NOT NULL,
  EstablishmentDate DATE NOT NULL,
  ClosureDate DATE NULL,
  Street VARCHAR(255) NOT NULL,
  StreetNumber NVARCHAR(255) NOT NULL
);

END