IF NOT EXISTS (
  SELECT
    *
  FROM
    INFORMATION_SCHEMA.TABLES
  WHERE
    TABLE_SCHEMA = 'map'
    AND TABLE_NAME = 'Location'
) BEGIN CREATE TABLE MAP.Location (
  Street VARCHAR(255) NOT NULL,
  StreetNumber NVARCHAR(255) NOT NULL,
  Longitude DECIMAL(12, 9) NOT NULL,
  Latitude DECIMAL(12, 9) NOT NULL,
  Suburban VARCHAR(255) NULL,
  City VARCHAR(255) NULL,
  PostalCode NVARCHAR(127) NULL,
  PRIMARY KEY (Street, StreetNumber)
);

END