IF NOT EXISTS (
  SELECT
    *
  FROM
    INFORMATION_SCHEMA.TABLES
  WHERE
    TABLE_SCHEMA = 'work'
    AND TABLE_NAME = 'WorkExperience'
) BEGIN CREATE TABLE WORK.WorkExperience (
  Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  Position VARCHAR(255) NOT NULL,
  Description VARCHAR(1023) NULL,
  StartDate DATE NOT NULL,
  EndDate DATE NULL,
  PartTime BIT NOT NULL,
  CompanyId UNIQUEIDENTIFIER NOT NULL,
  UserId UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT FK_WorkExperience_Company FOREIGN KEY (CompanyId) REFERENCES WORK.Company(Id),
  CONSTRAINT FK_WorkExperience_AspNetUsers FOREIGN KEY (UserId) REFERENCES OPENIDDICT.AspNetUsers(Id)
);

END